### ISSUE TITLE
Column headers

### ISSUE THREAD

**Issue by craibuc** [alekdavis/StreamLogging#4]
Column headers for files that are in CSV format would be helpful.  Perhaps added to the settings file?

**Comment by alekdavis** [comment]
I am thinking about it. If I ever get to implementing your suggestions, it will not be soon (just don't have time now). In the meantime, what you can do is: create a utility function where you print log entries in the format that you prefer (comma-separated, etc). Just don't use any built-in prefixes (time, log level) and add prefixes yourself (whatever you want) as part of the message. You can also print the headers yourself (as the first log call after you initialize the log settings). shouldn't take you longer than 20 minutes to do. This way you utilize the efficiency of the module (the primary goal) and can do whatever custom formatting that you desire.
